Tuan playback/thumbnail
nlstrait/Spark pull request #8
Opened 2021-05-25 07:12 UTC by Tuanthai4444

Fixed up some documentation to fit our needs. Also finished the slider for playback.

2021-05-25 20:33 UTC, nlstrait requested changes
Implementation looks good on the surface, but user tests reveal a couple of issues:
1. The slider value does not change as the track is played, so you can pick a starting position, but the slider stays in that position while playing, which is a bit unintuitive.
2. The stop button/function no longer works. It only resets playback to the start of the mixdown.

2021-05-25 20:33 UTC, nlstrait commented on Source/MixdownFolder.cpp
> +    audioPositionSlider.setRange(0, 0.1);
Is this range arbitrary since we'll set a new one when loading in a mixdown?

2021-05-25 20:47 UTC, jaygrinols commented
When there's only one mixdown in the selected folder, you can still press next/previous buttons. When navigating to a "blank" mixdown selection using these buttons in this state, it'll still play the previously selected mixdown. Might need to fix some functionality around there.

2021-05-25 21:13 UTC, Tuanthai4444 commented on Source/MixdownFolder.cpp
> +    audioPositionSlider.setRange(0, 0.1);
Yeah, range is arbitrary and we can instead set the slider to disabled if that's what we want?

2021-05-28 15:24 UTC, nlstrait commented
> When there's only one mixdown in the selected folder, you can still press next/previous buttons. When navigating to a "blank" mixdown selection using these buttons in this state, it'll still play the previously selected mixdown. Might need to fix some functionality around there.

I believe these issues are not specific to this branch / pull request but were here before. I have fixed some if not all of these issues in the branch I am currently working in.

2021-05-31 20:11 UTC, closed without merging

2021-05-31 20:11 UTC, Tuanthai4444 commented
We went with a different slider idea

2021-05-31 20:13 UTC, nlstrait commented
While running through xcode, upon application close, I get an error indicating that one or more objects have leaked. This suggests some objects may need to be explicitly deleted using `delete`.